// Package ormgen generates typed PostgreSQL data access from Fabrin model
// metadata.
//
// The generated Queries accepts the database/sql method set shared by *sql.DB,
// *sql.Tx, and *sql.Conn. Modules can keep declaring the narrow store ports they
// consume and satisfy them with generated methods at the wiring boundary.
package ormgen

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"go/token"
	"slices"
	"strings"
	"unicode"

	"github.com/usefabrin/fabrin/orm"
)

// ErrInvalidSchema means a declaration cannot produce valid, unambiguous Go
// and PostgreSQL code.
var ErrInvalidSchema = errors.New("ormgen: invalid schema")

// Generate returns a deterministic, gofmt-formatted Go source file containing
// row types and PostgreSQL Create/Get methods for models.
func Generate(packageName string, models []orm.Model) ([]byte, error) {
	checked, usesTime, err := validate(packageName, models)
	if err != nil {
		return nil, err
	}

	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by fabrin/ormgen. DO NOT EDIT.")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "package %s\n\n", packageName)
	fmt.Fprintln(&out, "import (")
	fmt.Fprintln(&out, ` "context"`)
	fmt.Fprintln(&out, ` "database/sql"`)
	fmt.Fprintln(&out, ` "fmt"`)
	if usesTime {
		fmt.Fprintln(&out, ` "time"`)
	}
	fmt.Fprintln(&out, ")")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "// DBTX is the database/sql method set used by Queries.")
	fmt.Fprintln(&out, "type DBTX interface {")
	fmt.Fprintln(&out, " ExecContext(context.Context, string, ...any) (sql.Result, error)")
	fmt.Fprintln(&out, " QueryRowContext(context.Context, string, ...any) *sql.Row")
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "// Queries executes generated statements against a database/sql handle.")
	fmt.Fprintln(&out, "type Queries struct { db DBTX }")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "// New returns generated queries backed by db.")
	fmt.Fprintln(&out, "func New(db DBTX) *Queries { return &Queries{db: db} }")

	for _, model := range checked {
		writeModel(&out, model)
	}

	source, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("%w: format generated source: %w", ErrInvalidSchema, err)
	}
	return source, nil
}

func writeModel(out *bytes.Buffer, model orm.Model) {
	fmt.Fprintln(out)
	fmt.Fprintf(out, "// %s is one row from %s.\n", model.GoName, model.Table)
	fmt.Fprintf(out, "type %s struct {\n", model.GoName)
	for _, field := range model.Fields {
		fmt.Fprintf(out, " %s %s\n", field.GoName, goType(field))
	}
	fmt.Fprintln(out, "}")

	columns := make([]string, 0, len(model.Fields))
	params := make([]string, 0, len(model.Fields))
	args := make([]string, 0, len(model.Fields))
	scans := make([]string, 0, len(model.Fields))
	var primary orm.Field
	for i, field := range model.Fields {
		columns = append(columns, quote(field.Name))
		params = append(params, fmt.Sprintf("$%d", i+1))
		args = append(args, "row."+field.GoName)
		scans = append(scans, "&row."+field.GoName)
		if field.PrimaryKey {
			primary = field
		}
	}

	createName := "create" + model.GoName
	getName := "get" + model.GoName
	fmt.Fprintln(out)
	fmt.Fprintf(out, "const %s = %q\n", createName,
		"INSERT INTO "+quote(model.Table)+" ("+strings.Join(columns, ", ")+") VALUES ("+strings.Join(params, ", ")+")")
	fmt.Fprintf(out, "const %s = %q\n", getName,
		"SELECT "+strings.Join(columns, ", ")+" FROM "+quote(model.Table)+" WHERE "+quote(primary.Name)+" = $1")

	fmt.Fprintln(out)
	fmt.Fprintf(out, "// Create%s inserts row.\n", model.GoName)
	fmt.Fprintf(out, "func (q *Queries) Create%s(ctx context.Context, row *%s) error {\n", model.GoName, model.GoName)
	fmt.Fprintln(out, " if row == nil { return fmt.Errorf(\"create "+model.Table+": row is nil\") }")
	fmt.Fprintf(out, " _, err := q.db.ExecContext(ctx, %s, %s)\n", createName, strings.Join(args, ", "))
	fmt.Fprintln(out, " if err != nil { return fmt.Errorf(\"create "+model.Table+": %w\", err) }")
	fmt.Fprintln(out, " return nil")
	fmt.Fprintln(out, "}")

	parameter := parameterName(primary.GoName)
	fmt.Fprintln(out)
	fmt.Fprintf(out, "// Get%s returns the row identified by its primary key.\n", model.GoName)
	fmt.Fprintf(out, "func (q *Queries) Get%s(ctx context.Context, %s %s) (*%s, error) {\n",
		model.GoName, parameter, goType(orm.Field{Type: primary.Type}), model.GoName)
	fmt.Fprintf(out, " var row %s\n", model.GoName)
	fmt.Fprintf(out, " if err := q.db.QueryRowContext(ctx, %s, %s).Scan(%s); err != nil {\n",
		getName, parameter, strings.Join(scans, ", "))
	fmt.Fprintln(out, "  return nil, fmt.Errorf(\"get "+model.Table+": %w\", err)")
	fmt.Fprintln(out, " }")
	fmt.Fprintln(out, " return &row, nil")
	fmt.Fprintln(out, "}")
}

func validate(packageName string, models []orm.Model) ([]orm.Model, bool, error) {
	if !token.IsIdentifier(packageName) || packageName == "_" {
		return nil, false, fmt.Errorf("%w: package name %q is not a Go identifier", ErrInvalidSchema, packageName)
	}
	if len(models) == 0 {
		return nil, false, fmt.Errorf("%w: no models", ErrInvalidSchema)
	}
	if err := orm.NewRegistry().Register("ormgen", models...); err != nil {
		return nil, false, fmt.Errorf("%w: %w", ErrInvalidSchema, err)
	}

	checked := slices.Clone(models)
	slices.SortFunc(checked, func(a, b orm.Model) int { return strings.Compare(a.GoName, b.GoName) })
	seenModels := make(map[string]bool, len(checked))
	usesTime := false
	for _, model := range checked {
		if !exportedIdentifier(model.GoName) {
			return nil, false, fmt.Errorf("%w: model Go name %q must be an exported Go identifier", ErrInvalidSchema, model.GoName)
		}
		if model.GoName == "DBTX" || model.GoName == "Queries" || model.GoName == "New" {
			return nil, false, fmt.Errorf("%w: model Go name %q collides with generated code", ErrInvalidSchema, model.GoName)
		}
		if seenModels[model.GoName] {
			return nil, false, fmt.Errorf("%w: model Go name %q appears twice", ErrInvalidSchema, model.GoName)
		}
		seenModels[model.GoName] = true
		if !sqlIdentifier(model.Table) {
			return nil, false, fmt.Errorf("%w: table name %q must be a lowercase SQL identifier", ErrInvalidSchema, model.Table)
		}

		seenFields := make(map[string]bool, len(model.Fields))
		primaries := 0
		for _, field := range model.Fields {
			if !exportedIdentifier(field.GoName) {
				return nil, false, fmt.Errorf("%w: field Go name %q on %s must be an exported Go identifier", ErrInvalidSchema, field.GoName, model.GoName)
			}
			if seenFields[field.GoName] {
				return nil, false, fmt.Errorf("%w: field Go name %q appears twice on %s", ErrInvalidSchema, field.GoName, model.GoName)
			}
			seenFields[field.GoName] = true
			if !sqlIdentifier(field.Name) {
				return nil, false, fmt.Errorf("%w: column name %q on %s must be a lowercase SQL identifier", ErrInvalidSchema, field.Name, model.GoName)
			}
			if field.PrimaryKey {
				primaries++
				if field.Nullable {
					return nil, false, fmt.Errorf("%w: primary key %s.%s cannot be nullable", ErrInvalidSchema, model.Table, field.Name)
				}
			}
			usesTime = usesTime || field.Type == orm.TypeTime
		}
		if primaries != 1 {
			return nil, false, fmt.Errorf("%w: model %s has %d primary keys; generated Get requires exactly one", ErrInvalidSchema, model.GoName, primaries)
		}
	}
	return checked, usesTime, nil
}

func exportedIdentifier(name string) bool {
	return token.IsIdentifier(name) && token.IsExported(name)
}

func sqlIdentifier(name string) bool {
	if name == "" || name[0] < 'a' || name[0] > 'z' {
		return false
	}
	for _, r := range name[1:] {
		if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '_' {
			return false
		}
	}
	return true
}

func goType(field orm.Field) string {
	base := map[orm.Type]string{
		orm.TypeString: "string",
		orm.TypeInt:    "int",
		orm.TypeInt64:  "int64",
		orm.TypeFloat:  "float64",
		orm.TypeBool:   "bool",
		orm.TypeTime:   "time.Time",
		orm.TypeBytes:  "[]byte",
	}[field.Type]
	if field.Nullable && field.Type != orm.TypeBytes {
		return "*" + base
	}
	return base
}

func quote(name string) string { return `"` + name + `"` }

func parameterName(name string) string {
	runes := []rune(name)
	end := 1
	for end < len(runes) && unicode.IsUpper(runes[end]) {
		if end+1 < len(runes) && unicode.IsLower(runes[end+1]) {
			break
		}
		end++
	}
	for i := 0; i < end; i++ {
		runes[i] = unicode.ToLower(runes[i])
	}
	out := string(runes)
	if out == "ctx" || token.Lookup(out).IsKeyword() {
		return out + "Value"
	}
	return out
}
