// Code generated by fabrin/ormgen. DO NOT EDIT.

package orderdb

import (
	"context"
	"database/sql"
	"fmt"
	"time"
)

// DBTX is the database/sql method set used by Queries.
type DBTX interface {
	ExecContext(context.Context, string, ...any) (sql.Result, error)
	QueryRowContext(context.Context, string, ...any) *sql.Row
}

// Queries executes generated statements against a database/sql handle.
type Queries struct{ db DBTX }

// New returns generated queries backed by db.
func New(db DBTX) *Queries { return &Queries{db: db} }

// Order is one row from order.
type Order struct {
	ID        int64
	Reference string
	Quantity  int
	Total     float64
	Active    bool
	Payload   []byte
	Note      *string
	ShippedAt *time.Time
}

const createOrder = "INSERT INTO \"order\" (\"id\", \"reference\", \"quantity\", \"total\", \"active\", \"payload\", \"note\", \"shipped_at\") VALUES ($1, $2, $3, $4, $5, $6, $7, $8)"
const getOrder = "SELECT \"id\", \"reference\", \"quantity\", \"total\", \"active\", \"payload\", \"note\", \"shipped_at\" FROM \"order\" WHERE \"id\" = $1"

// CreateOrder inserts row.
func (q *Queries) CreateOrder(ctx context.Context, row *Order) error {
	if row == nil {
		return fmt.Errorf("create order: row is nil")
	}
	_, err := q.db.ExecContext(ctx, createOrder, row.ID, row.Reference, row.Quantity, row.Total, row.Active, row.Payload, row.Note, row.ShippedAt)
	if err != nil {
		return fmt.Errorf("create order: %w", err)
	}
	return nil
}

// GetOrder returns the row identified by its primary key.
func (q *Queries) GetOrder(ctx context.Context, id int64) (*Order, error) {
	var row Order
	if err := q.db.QueryRowContext(ctx, getOrder, id).Scan(&row.ID, &row.Reference, &row.Quantity, &row.Total, &row.Active, &row.Payload, &row.Note, &row.ShippedAt); err != nil {
		return nil, fmt.Errorf("get order: %w", err)
	}
	return &row, nil
}
